# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160206_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='blog.UserProfile'),
        ),
    ]
