# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_blog',
            field=models.CharField(default='', max_length=100),
        ),
    ]
