# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile_main_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='main_blog',
            field=models.IntegerField(default=0),
        ),
    ]
